export const STATIONS = {
  Delhi: [
    'New Delhi Railway Station (NDLS)',
    'Hazrat Nizamuddin (NZM)',
    'Delhi Junction (DLI)',
    'Anand Vihar Terminal (ANVT)',
    'IGI Airport Terminal 1',
    'IGI Airport Terminal 2/3',
    'ISBT Kashmere Gate',
    'ISBT Anand Vihar',
    'Sarai Kale Khan Bus Stand',
  ],
  Mumbai: [
    'Chhatrapati Shivaji Maharaj Terminus (CSMT)',
    'Mumbai Central (BCT)',
    'Bandra Terminus (BDTS)',
    'Lokmanya Tilak Terminus (LTT)',
    'Chhatrapati Shivaji Maharaj International Airport (T1)',
    'Chhatrapati Shivaji Maharaj International Airport (T2)',
    'Mumbai Central Bus Depot',
    'Borivali Bus Station',
  ],
  Bangalore: [
    'Krantivira Sangolli Rayanna (KSR) Railway Station',
    'Yesvantpur Junction (YPR)',
    'Byappanahalli Station',
    'Kempegowda International Airport (T1)',
    'Kempegowda International Airport (T2)',
    'Majestic / Kempegowda Bus Stand',
    'Shivajinagar Bus Stand',
    'Satellite Bus Stand (Mysuru Road)',
  ],
  Chennai: [
    'Chennai Central (MAS)',
    'Chennai Egmore (MS)',
    'Tambaram Railway Station',
    'Chennai International Airport (T1 Domestic)',
    'Chennai International Airport (T2 International)',
    'CMBT (Koyambedu Bus Terminus)',
    'Chennai Mofussil Bus Terminus',
  ],
  Hyderabad: [
    'Hyderabad Deccan (Nampally)',
    'Secunderabad Junction (SC)',
    'Kacheguda Station',
    'Rajiv Gandhi International Airport (T1)',
    'Rajiv Gandhi International Airport (T2)',
    'Mahatma Gandhi Bus Station (MGBS)',
    'Jubilee Bus Station (JBS)',
    'Uppal Bus Stand',
  ],
  Kolkata: [
    'Howrah Junction (HWH)',
    'Sealdah Station (SDAH)',
    'Shalimar Station',
    'Netaji Subhas Chandra Bose Airport',
    'Esplanade Bus Terminus',
    'Dharmatala Bus Stand',
    'Babughat Bus Stand',
  ],
  Pune: [
    'Pune Junction (PUNE)',
    'Shivajinagar Station',
    'Hadapsar Station',
    'Pune International Airport',
    'Pune Railway Station Bus Stand',
    'Swargate Bus Stand',
    'Shivajinagar Bus Stand',
  ],
  Ahmedabad: [
    'Ahmedabad Junction (ADI)',
    'Sabarmati Junction',
    'Gandhinagar Capital Station',
    'Sardar Vallabhbhai Patel International Airport',
    'Paldi Bus Stand (ST Bus)',
    'Naroda Bus Stand',
    'Geeta Mandir Bus Stand',
  ],
  Jaipur: [
    'Jaipur Junction (JP)',
    'Gandhinagar Jaipur Station',
    'Sanganer Airport (Jaipur International)',
    'Sindhi Camp Bus Stand',
    'Narayan Singh Circle Bus Stand',
    'Central Bus Stand',
  ],
  Lucknow: [
    'Lucknow Charbagh (LKO)',
    'Lucknow Junction (LJN)',
    'Amausi International Airport (LKO)',
    'Charbagh Bus Stand',
    'Kaiserbagh Bus Stand',
    'Alambagh Bus Stand',
  ],
  Chandigarh: [
    'Chandigarh Railway Station (CDG)',
    'Chandigarh Airport (IXC)',
    'ISBT Sector 43',
    'ISBT Sector 17',
    'Inter State Bus Terminal',
  ],
  Kochi: [
    'Ernakulam Junction (ERS)',
    'Ernakulam Town (ERN)',
    'Cochin International Airport (T1)',
    'Cochin International Airport (T2)',
    'KSRTC Bus Stand Ernakulam',
    'High Court Junction Bus Stand',
  ],
  Bhopal: [
    'Bhopal Junction (BPL)',
    'Habibganj Station (HBJ)',
    'Raja Bhoj Airport',
    'ISBT Bhopal',
    'Nadra Bus Stand',
  ],
  Patna: [
    'Patna Junction (PNBE)',
    'Rajendra Nagar Terminal',
    'Jay Prakash Narayan Airport',
    'Patna Bus Stand (Gandhi Maidan)',
    'Mithapur Bus Stand',
  ],
  Surat: [
    'Surat Station (ST)',
    'Udhna Junction (UDN)',
    'Surat Airport',
    'Central Bus Stand Surat',
    'Kapodra Bus Stand',
  ],
};
